dkanada/frost

- other/fennec.svg
I made this icon mostly to practice using inkscape, but i noticed the Fennec icon in frost kinda just looks like a rabbit, so feel free to replace it with this if you want.
Probably gonna try making icons for some apps that don't already have one as well.
> New fennec icon

- other/swish.svg
se.bankgirot.swish/se.bankgirot.swish.ui.SplashActivity
Icon for a swedish payment app, i hope it being proprietary isn't a problem.
> Swish icon

- other/kdeconnect.svg
org.kde.kdeconnect_tp/org.kde.kdeconnect.UserInterface.MainActivity
> Kdeconnect icon

- other/simpleapplauncher.svg
- other/simplecalculator.svg
- other/simplecalendar.svg
- other/simplecamera.svg
- other/simpleclock.svg
- other/simplecontacts.svg
- other/simpledraw.svg
- other/simplefilemanager.svg
- other/simpleflashlight.svg
- other/simplegallery.svg
- other/simplemusicplayer.svg
- other/simplenotes.svg
Fixes some of #85
Calculator: com.simplemobiletools.calculator/com.simplemobiletools.calculator.activities.SplashActivity
Calendar: com.simplemobiletools.calendar/com.simplemobiletools.calendar.activities.SplashActivity
Camera: com.simplemobiletools.camera/com.simplemobiletools.camera.activities.SplashActivity
Contacts: com.simplemobiletools.contacts/com.simplemobiletools.contacts.activities.SplashActivity
Draw: com.simplemobiletools.draw/com.simplemobiletools.draw.activities.SplashActivity
File Manager: com.simplemobiletools.filemanager/com.simplemobiletools.filemanager.activities.SplashActivity
Flashlight: com.simplemobiletools.flashlight/com.simplemobiletools.flashlight.activities.SplashActivity
Gallery: com.simplemobiletools.gallery/com.simplemobiletools.gallery.activities.SplashActivi …
> Simple apps

- README.md
the fdroid link initially brought me to a 404
> youve got some old links there bud

- app/src/main/res/xml/appfilter.xml
Simply add the Facebook Messenger icon for [Messenger Lite](https://play.google.com/store/apps/details?id=com.facebook.mlite&hl=en).
> Add Messenger Lite icon

- other/kdeconnect.svg
Adds new logo for KDEConnect app.
> Kdeconnect

- other/telegram.svg
> Adds new Telegram logo

- app/src/main/res/values-nb-rNO/strings.xml
- app/src/main/res/values-nn/strings.xml
- metadata/nb-NO/full_description.txt
- metadata/nb-NO/short_description.txt
- metadata/nn-NO/full_description.txt
- metadata/nn-NO/short_description.txt
This should localize the app for devices that use these locales, and also make the icon show up on F-Droid for those devices in the native language.
> Add Norwegian (bokmål and nynorsk) localizations

- .gitignore
- app/src/main/res/xml/appfilter.xml
- other/knockonports.svg
- other/towercollector.svg
Added icon for Tower Collector
Added icon for Knock on Ports
> 2 new icons

- other/bandcamp.svg
- other/dark sky.svg
- other/deco.svg
- other/korader.svg
bandcamp.svg -> com.bandcamp.android/com.bandcamp.android.view.SplashActivity
dark sky.svg -> net.darksky.darksky/net.darksky.darksky.DarkSky
deco.svg -> com.tplink.tpm5/com.tplink.tpm5.view.welcome.WelcomeActivity
korader.svg -> org.koreader.launcher/org.koreader.launcher.MainActivity
> new handmade icons

- app/src/main/res/xml/appfilter.xml
- other/bandsintown.svg
Adds logo for [Bandsintown](https://www.bandsintown.com/en) app
> Adds Bandsintown app logo

- app/src/main/res/xml/appfilter.xml
> add crDroid defaul dialer

- app/src/main/res/xml/appfilter.xml
Adds classes to `appfilter.xml` for icons that already in the repo but changed their class name after updates
> Return missed icons

- app/src/main/res/xml/appfilter.xml
Fix a couple of typos, and add another entry for updated mgit package activity name.
> Minor fixes

- app/src/main/res/xml/appfilter.xml
- other/facebook-lite.svg
Hi, this is my very first attempt in vector drawing and I wanted to practice on something useful. So this probably will need some improvement, but I am willing to learn :stuck_out_tongue:
> added icon for facebook lite

- app/src/main/res/xml/appfilter.xml
- other/compass.svg
- other/mimusic.svg
- other/miuisecurity.svg
- other/miuiweather.svg
- other/mivideo.svg
- other/scanner.svg
- other/screenrecorder.svg
- other/shareme.svg
This adds support for the default apps in Xiaomi MIUI and includes some missing icons.
Application info gathered from MIUI 10, but should work with other versions.
> Added support for Xiaomi default apps

- app/src/main/res/xml/appfilter.xml
- other/libby.svg
Created an icon for the Libby app and added it to the appfilter
> Icon for Libby

- app/src/main/res/xml/appfilter.xml
- other/freezer.svg
This PR adds Freezer's icon (https://git.rip/freezer/freezer).
> Add Freezer icon

- other/ultrasonic.svg
Output from turtl:
`
<item component="ComponentInfo{org.moire.ultrasonic/org.moire.ultrasonic.activity.NavigationActivity}" drawable="ultrasonic"/>`
> Add icon for Ultrasonic

- other/vk.svg
> Larger vk.svg
